### PR TITLE
Implement local run with Docker

### PR DESCRIPTION
**Pull request by errge**
Please note that I'm still running the slow test run (with the 3 kernel builds) on my machine, so the build dependencies in the Dockerfile might need to be extended, I will get back to you.

The project fully works and already tested when the 3 build tests are excluded in `nipa.config`.

### CODE REVIEW

**Comment by errge** [comment]
Replaced reflink=always with reflink=auto, so it works even with ext4 (although slowly compared to xfs or btrfs).

I do the big copy by-the-way, as a precaution to make sure that nipa under no circumstances messes up the given linux git tree.  Maybe this is too paranoid and we shouldn't do this?  It messed up mine when I ctrl-c'd at a random time.

**Comment by kuba-moo** [comment]
First off - great stuff, thanks for doing this.

On the copy, I believe that if you use git clone within a subsystem git will automatically use hard-links for git objects, and the clone should be really fast, no? Is the `cp` version faster?

**Comment by errge** [comment]
I did some testing on the CoW thing on a fresh BTRFS, the results are:

```
reflink always:
  time: 4.5s
  space: 132192
  rm: 1.7s

git clone:
  time: 11.6s
  space: 1511376
  rm: 2.0s
```

So the current solution is ~6s faster and consumes 100M space (compared to 1.5G for git clone).

The git clone was totally naive, I didn't look into all the flags of git to share even more data or something, but I verified the inode count at least to make sure that the hard linking was functional, so I think the extra space and time mostly went into preparing the working copy, that git had to do from actual computation code, while btrfs reflink could cheat with its abstraction.

My proposal (since it's only 3 lines of code): I modify reflink to always (not auto), but if I get an error message, I do a git clone and a warning message that the project works better on btrfs/xfs.  Good enough?

**Comment by errge** [comment]
I have a bigger problem though, now that I had time (during the night) to run all the tests: all the build tests are failing:

```
start: 02:16
finish: 06:38

0	nipa-run/results/1/tree_selection/retcode
1	nipa-run/results/1/1/build_32bit/retcode
1	nipa-run/results/1/1/build_allmodconfig_warn/retcode
1	nipa-run/results/1/1/build_clang/retcode
0	nipa-run/results/1/1/cc_maintainers/retcode
0	nipa-run/results/1/1/check_selftest/retcode
0	nipa-run/results/1/1/checkpatch/retcode
0	nipa-run/results/1/1/header_inline/retcode
0	nipa-run/results/1/1/kdoc/retcode
0	nipa-run/results/1/1/module_param/retcode
250	nipa-run/results/1/1/signed/retcode
0	nipa-run/results/1/1/source_inline/retcode
0	nipa-run/results/1/1/verify_fixes/retcode
0	nipa-run/results/1/1/verify_signedoff/retcode
0	nipa-run/results/1/cover_letter/retcode
0	nipa-run/results/1/fixes_present/retcode
0	nipa-run/results/1/patch_count/retcode
0	nipa-run/results/1/subject_prefix/retcode
```

It takes 4 hours 20 minutes on an OK desktop machine (not as beefy as Linus get as a present, but also not a grandma' laptop).  The failures are coming from countless and countless warnings that absolutely don't show up on patchwork bot at all.  Is it running with a different configuration?  Also, for patchworks the whole stuff is done in ~10-20 minutes, which seems unreal to me.

I was hoping that the difference is coming from somehow first and second run regarding ccache, so now I'm doing a second run with the ccache saved from the previous run, but I'm in it for 1 hour and it still haven't finished build_32bit, so it won't be any better.

Can you give advice what I'm doing wrong and how to match patchworks?

**Comment by errge** [comment]
Added the ccache sharing code and the results.sh script to get the output that I copy-pasted.

**Comment by errge** [comment]
One more thing: I'm sure you noticed the git usename hacking, I had to do.

I just added a comment on this, to explain the necessity, tldr: `git-am -s` adds an extra signoff, which if matches the original signoff, then the `checkpatch` test fails with `Duplicate signature`.

My question: can we remove the `-s` from `git-am`, why is it there? (And also `git pull --signoff`.)

I don't understand the rationale, and there is no explanation in `core/tree.py`, I think this can even mask an issue: if the noobie developer forgets to add any signoff, then nipa automatically adds one, and then the `checkpatch` will not notice the fact that there are zero signoffs.

**Comment by errge** [comment]
Implemented reflink always workaround

**Comment by errge** [comment]
Added comment on git username hacking

**Comment by errge** [comment]
Fix reflink always workaround to actually work

**Comment by errge** [comment]
Fixed a bug when the developer leaves his git repo on nipa-local (good that you asked about reflink always, otherwise I wouldn't have found this corner case).

**Comment by errge** [comment]
Added `--read-only` to docker, so we know that no other cache is used outside of `~/.ccache`, and for general cleanliness and reproducibility.

**Comment by errge** [comment]
Setting TMPDIR to somewhere and then making /tmp read-only causes a GNU make segfault (because of a libc bug, I checked).  Be less aggressive with this read-only idea, and just expose /tmp normally.

**Comment by errge** [comment]
Yes, even with ccache fully cached, the build is not as short as on patchwork, here is the stderr: https://www.filemail.com/d/hadfyuiocrnazgp

**Comment by kuba-moo** [comment]
The only thing which comes to mind for the build speed is making the ccache size larger (`ccache -M`). If you're touching any often-included file like skbuff.h the build will take for ever. The script doubles the number of builds because it builds before and after each change to compare the outputs. PW bot runs on the biggest available AWS VM.

I think the lack of signoffs may trip up `verify_signedoff`, if all the tests pass without them we can certainly drop them.

**Comment by errge** [comment]
Hey @kuba-moo Thank you for your answers, I can try tuning up ccache, but my problem with the uplodaded stderr still stands: on the PW bot builds, we don't have megabytes of warnings, on my local build, I do.  So it's not just speed, the result is incorrect.  Do you have any idea why?

About signedoff: I will test out with turned off and report back tomorrow.

**Comment by kuba-moo** [comment]
Depends on the patch, the initial build is always enormous (note that we're building with W=1)! Initial build or build which touched a major header will be big, for example:
https://patchwork.hopto.org/static/nipa/715107/13113999/build_32bit/stderr
If the results is success that means the number of warnings did not increase, so all is good.

**Comment by errge** [comment]
Sorry, I was not explicit enough, the stuff is failing: as I showed before all the build outputs have retcode 1, not zero, and when I look into summary or desc (don't remember), then I see that it says something like "incumbent 7 warnings, after patch 221 warnings".

And my patch is a super innocent one liner change in a .c file, not even a header.

OK, I will try to understand these build shell scripts, removed the rm from it, so I can compare the outputs myself.  I'm not sure I will be able to debug this, but now I give it another couple of hours to finish and look into the results tomorrow.

**Comment by kuba-moo** [comment]
Hm. The logic for counting the warnings may be a little shaky when run for a mbox, I guess. Good news is the scripts should be pretty self contained, IIRC, so you can run just the shell script with minimal changes.
I've seen the script get confused by pull requests, but for patches when run in patchwork mode - I don't remember issues.

**Comment by PavanC-BRCM** [comment]
hi errge, I am trying to run this and I see this error -
Error: statfs /<my nipa dir>/nipa/docker/ccache: no such file or directory
Trying to figure out in the meanwhile I thought I could just let you know if this is something you know already.

**Comment by errge** [comment]
@PavanC-BRCM Thank you for trying to test this.  I think an `mkdir ccache` was missing from the code.  I added this in the last force push, can you please pull and give it a try again with the `./run.sh`?  Cheers!

**Comment by errge** [comment]
@kuba-moo Yes, this was 100% user-error, finally it seems to work.

What happened is that my base commit I was standing on was buggy, I even found in git history a fix from yesterday that fixed the build issue.  It was just hard to see the error message before I uncommented the temporary files rm from the script.

build32 works now, I'm running the other builds during the night and will report back tomorrow, my guess is that we are ready to merge this, but please wait my final OK and provide me feedback if there is still things to fix.  I'll be away thursdaynight-sunday, so it would be great to get to a stage by tomorrow that I can fix any remaining concerns and if all build works, you can just merge.

I have a couple of ideas on what to improve to make the local user experience nicer, I will open tickets to discuss and then I can implement them next week if you give your pre-approval.

**Comment by errge** [comment]
Oh, issues are disabled for this repo, then here we go, ideas in difficulty order (easiest first):

  - rename build* to zbuild* to make sure that the very slow stuff runs last, so the developer has time to fix the trivial issues in the meantime (style check, maintainers cc, etc.),
  - remove `rm $tmpfile` from all `build*.sh` if we detect that we are inside docker, the `/tmp` directory is separated from the system anyways, and this gives extra debugging capabilities to the enduser,
  - modify the scripts that the output is not only printed when everything is finished, but instead continuously when a test succeeds/fails.  I haven't checked how hard this is yet, and it would make sense mostly only if we are in agreement with the zbuild rename.

Can you please give me your feedback regarding these, so I can implement only those that you agree with.  Of course, I will start separate PRs and not put more stress on this one.

If you think all of this is superfluous, I can accept that, if the build works out during the night, then current state of nipa is good enough for me for my netdev hacking needs.

**Comment by kuba-moo** [comment]
Keeping the full logs for local runs makes sense.

The rename to zbuild will only make a difference if you have a single patch, commonly people post multi-patch series and since tester runs patch-by-patch the ordering gains will quickly disappear. The idea seems good tho, in principle. Instead of the rename I'd rather we marked the tests as "slow" in the JSON file, and sort within the Python code. Smaller chance the "z-name" will leak somewhere and look odd.

The continuous output sounds great. Can that be handled within the `ingest_mdir.py` code completely or do we need core changes? For PW as you probably saw I used file system notifications to reap results and upload to PW.

**Comment by PavanC-BRCM** [comment]
hi @errge Let me check with your latest changes. BTW, yesterday I had to edit Dockerfile to have -o for the useradd otherwise it would not let me run as root. As below: 
RUN useradd -o -m -u $nipauid nipa

**Comment by errge** [comment]
@PavanC-BRCM Ahh, good point, I didn't think of people who want to run this as root at all.  Why do you want to do that?  Anyway, please report back how it goes, sounds interesting!

**Comment by errge** [comment]
@kuba-moo Thanks for the instructions for next week, I will use them when I get there.

About this pull request, the midnight run finished:

```
Build nipa docker image...
Sending build context to Docker daemon  13.31kB
Step 1/6 : FROM debian:bookworm
 ---> 0860729d0489
Step 2/6 : ARG nipauid
 ---> Using cache
 ---> 54a404b23bc3
Step 3/6 : RUN useradd -m -u $nipauid nipa
 ---> Using cache
 ---> d6f54d4bfb8d
Step 4/6 : RUN apt-get update
 ---> Using cache
 ---> 363678730d5e
Step 5/6 : RUN apt-get install -y procps python3 git patatt build-essential         ccache flex bison libssl-dev libelf-dev clang sparse bc cpio         gdb strace vim
 ---> Using cache
 ---> 86fff627be02
Step 6/6 : RUN mkdir -p /home/nipa/.local/share/patatt && chown -R nipa: /home/nipa
 ---> Using cache
 ---> fed7c89c658a
Successfully built fed7c89c658a
Successfully tagged nipa-local:latest
Removing previous nipa-run...
Creating CoW tree...
Switched to a new branch 'nipa-local-tmp-6fd3e4661f'
Running nipa in Docker...
==========
build_32bit - OKAY
Errors and warnings before: 0 this patch: 0
==========
build_allmodconfig_warn - OKAY
Errors and warnings before: 0 this patch: 0
==========
build_clang - OKAY
Errors and warnings before: 0 this patch: 0
==========
cc_maintainers - OKAY
CCed 7 of 7 maintainers
==========
check_selftest - OKAY
No net selftest shell script
==========
checkpatch - WARNING
WARNING: line length of 82 exceeds 80 columns
==========
header_inline - OKAY
No static functions without inline keyword in header files
==========
kdoc - OKAY
Errors and warnings before: 0 this patch: 0
==========
module_param - OKAY
Was 0 now: 0
==========
signed - WARNING
No signature found. Please sign patches: https://github.com/mricon/patatt
==========
source_inline - OKAY
Was 0 now: 0
==========
verify_fixes - OKAY
Fixes tag looks correct
==========
verify_signedoff - OKAY
Signed-off-by tag matches author and committer
==========
cover_letter - OKAY
Single patches do not need cover letters
==========
fixes_present - OKAY
Fixes tag not required for -next series
==========
patch_count - OKAY
==========
subject_prefix - OKAY
```

As you can see, it's all successful, the build_* tests work too, so I think we are ready to merge.

**Comment by errge** [comment]
@PavanC-BRCM Implemented support to run this as root, thinking about it, it makes sense.  I guess kernel development are done by a lot of people in VMs already (for speed in the cloud or for other reasons), and it completely makes sense, that on those machines/environments we don't always have our users set up, we simply run as root.

Supporting this required a bit of extra testing and hacking, but now it works both as a user and as root.

**Pull request merged**
